# Welcome to the Brick Config! You may edit this file to customize your build.

# Directory Config
$Env:BRICKS_ROOT_DIR = "brick"
$Env:TMP_DIR = "${BRICKS_ROOT_DIR}/tmp"
$Env:BUILD_DIR = "${BRICKS_ROOT_DIR}/build"
$Env:INSTALL_DIR = "${BRICKS_ROOT_DIR}/install"

# Compiler Config
$Env:COMPILER_DIR = "C:\MinGW\bin\gcc.exe"
$Env:CC = "gcc"
$Env:CXX = "g++"
$Env:FC = "gfortran"
$Env:MPICC = "mpicc"
$Env:MPICXX = "mpicxx"
$Env:MPIFC = "mpif90"

# Compilation Options
$Env:GLOBAL_CFLAGS = ""
$Env:GLOBAL_CXXFLAGS = ""
$Env:GLOBAL_FFLAGS = ""
$Env:NUM_THREADS = "$(Get-CimInstance -ClassName Win32_Processor | Select-Object -ExpandProperty NumberOfLogicalProcessors)"

# End of Brick Config


# The following options should not be edited
$Env:FMT_RESET = "\e[0m"
$Env:FMT_COLOR_BLACK = "\e[30m"
$Env:FMT_COLOR_RED = "\e[31m"
$Env:FMT_COLOR_GREEN = "\e[32m"
$Env:FMT_COLOR_YELLOW = "\e[33m"
$Env:FMT_COLOR_BLUE = "\e[34m"
$Env:FMT_COLOR_MAGENTA = "\e[35m"
$Env:FMT_COLOR_CYAN = "\e[36m"
$Env:FMT_COLOR_WHITE = "\e[37m"
$Env:FMT_COLOR_BRIGHT_BLACK = "\e[90m"
$Env:FMT_COLOR_BRIGHT_RED = "\e[91m"
$Env:FMT_COLOR_BRIGHT_GREEN = "\e[92m"
$Env:FMT_COLOR_BRIGHT_YELLOW = "\e[93m"
$Env:FMT_COLOR_BRIGHT_BLUE = "\e[94m"
$Env:FMT_COLOR_BRIGHT_MAGENTA = "\e[95m"
$Env:FMT_COLOR_BRIGHT_CYAN = "\e[96m"
$Env:FMT_COLOR_BRIGHT_WHITE = "\e[97m"
$Env:FMT_BG_BLACK = "\e[40m"
$Env:FMT_BG_RED = "\e[41m"
$Env:FMT_BG_GREEN = "\e[42m"
$Env:FMT_BG_YELLOW = "\e[43m"
$Env:FMT_BG_BLUE = "\e[44m"
$Env:FMT_BG_MAGENTA = "\e[45m"
$Env:FMT_BG_CYAN = "\e[46m"
$Env:FMT_BG_WHITE = "\e[47m"
$Env:FMT_BG_BRIGHT_BLACK = "\e[100m"
$Env:FMT_BG_BRIGHT_RED = "\e[101m"
$Env:FMT_BG_BRIGHT_GREEN = "\e[102m"
$Env:FMT_BG_BRIGHT_YELLOW = "\e[103m"
$Env:FMT_BG_BRIGHT_BLUE = "\e[104m"
$Env:FMT_BG_BRIGHT_MAGENTA = "\e[105m"
$Env:FMT_BG_BRIGHT_CYAN = "\e[106m"
$Env:FMT_BG_BRIGHT_WHITE = "\e[107m"
$Env:FMT_BOLD = "\e[1m"
$Env:FMT_DIM = "\e[2m"
$Env:FMT_ITALIC = "\e[3m"
$Env:FMT_UNDERLINE = "\e[4m"
$Env:FMT_BLINK = "\e[5m"
$Env:FMT_REVERSE = "\e[7m"
$Env:FMT_HIDDEN = "\e[8m"
$Env:FMT_STRIKETHROUGH = "\e[9m"
$Env:FMT_RESET_BOLD_DIM = "\e[22m"
$Env:FMT_RESET_ITALIC = "\e[23m"
$Env:FMT_RESET_UNDERLINE = "\e[24m"
$Env:FMT_RESET_BLINK = "\e[25m"
$Env:FMT_RESET_REVERSE = "\e[27m"
$Env:FMT_RESET_HIDDEN = "\e[28m"
$Env:FMT_RESET_STRIKETHROUGH = "\e[29m"
# End of Config
