name: Build BRICK

env:
  VERSION: A1.0

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build BRICK (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        arch: [x86_64, arm64]
        include:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: '17'

      - name: Cache sbt
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: sbt-cache-${{ matrix.arch }}-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            sbt-cache-${{ matrix.arch }}-

      - name: Install LLVM and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang lld libunwind-dev

      - name: Compile
        run: sbt nativeLink

      - name: Upload Native Binary
        uses: actions/upload-artifact@v4
        with:
          name: brick-linux-${{ matrix.arch }}
          path: target/scala-*/brick

      - name: Prepare nfpm
        run: |
          if [ "${{ matrix.arch }}" = "x86_64" ]; then
            echo "NFPM_ARCH=amd64" >> $GITHUB_ENV
            echo "RPM_ARCH=x86_64" >> $GITHUB_ENV
          else
            echo "NFPM_ARCH=arm64" >> $GITHUB_ENV
            echo "RPM_ARCH=aarch64" >> $GITHUB_ENV
          fi
          mkdir -p dist
          mkdir -p bin
          cp target/scala-*/brick bin/brick
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt update
          sudo apt install nfpm
      
      - name: Build Packages
        run: |
          nfpm pkg --packager deb \
            --config share/nfpm/${NFPM_ARCH}.yaml \
            --target dist/brick_${VERSION}_${NFPM_ARCH}.deb

          nfpm pkg --packager rpm \
            --config share/nfpm/${NFPM_ARCH}.yaml \
            --target dist/brick-${VERSION}-1.${RPM_ARCH}.rpm

      - name: Checkout apt-repo
        uses: actions/checkout@v3
        with:
          repository: Cy4Shot/repo
          path: apt-repo

      - name: Copy packages into apt-repo
        run: |
          mkdir -p apt-repo/debian/incoming
          cp dist/*.deb apt-repo/debian/incoming/
          
          mkdir -p apt-repo/rpm/
          cp dist/*.rpm apt-repo/rpm/

      - name: Install reprepro and createrepo
        run: |
          sudo apt install -y guix reprepro
          guix install createrepo-c

      - name: Update Debian repo with reprepro
        run: |
          cd apt-repo/debian
          for f in incoming/*.deb; do
            reprepro -Vb . includedeb stable "$f"
          done
          rm -rf incoming

      - name: Update YUM repo with createrepo
        run: |
          createrepo_c --update apt-repo/rpm

      - name: Commit & push updated repo
        run: |
          cd apt-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update package repo with new packages"
          git push
