name: Build BRICK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        arch: [x86_64, arm64]
        include:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache sbt
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: sbt-cache-${{ matrix.arch }}-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            sbt-cache-${{ matrix.arch }}-

      - name: Install LLVM and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang lld libunwind-dev

      - name: Compile and Test
        run: sbt nativeLink test

      - name: Upload Native Binary
        uses: actions/upload-artifact@v4
        with:
          name: brick-linux-${{ matrix.arch }}
          path: target/scala-*/brick
